### PR TITLE
add clnn and cltorch

### PR DESCRIPTION
**Pull request by hughperkins**
add clnn and cltorch

### CODE REVIEW

**Comment by soumith** [comment]
Yaay!!!

**Comment by hughperkins** [comment]
cool :-)

**Comment by hughperkins** [comment]
Hmmm, seems I have some debugging to do :-P  to get it to do git recursive somehow.

**Comment by hughperkins** [comment]
Hmmm ,seems luarocks/fetch/git.lua deletes the .git directory :-P

Lines 83 and 84:

```
   fs.delete(dir.path(store_dir, module, ".git"))
   fs.delete(dir.path(store_dir, module, ".gitignore"))
```

So .... erm ... interesting :-P

**Comment by soumith** [comment]
Hmmmm is it a problem?

**Comment by hughperkins** [comment]
Well, it means git submodule wont work.  There's a ton of ways I can work around the issue though, eg create a 'cltorch-bootstrap' repo, which then git clones the real cltorch repo.

**Pull request merged**
